export const DOCKED_TOOLBAR_HEIGHT = 44
export const DOCKED_TOOLBAR_PADDING_Y = 6
export const DOCKED_TOOLBAR_PADDING_X = 8
export const DOCKED_TOOLBAR_BUTTON_SIZE = 32

export const DOCKED_PANE_BACKGROUND = '#121212'

export const DEFAULT_DOCKED_OUTLINE_WIDTH = 240
export const DEFAULT_DOCKED_DETAILS_WIDTH = 350
export const DEFAULT_DOCKED_SEQUENCER_HEIGHT = 280

export const MIN_DOCKED_OUTLINE_WIDTH = 180
export const MIN_DOCKED_DETAILS_WIDTH = 280
export const MIN_DOCKED_SEQUENCER_HEIGHT = 200

export const MAX_DOCKED_OUTLINE_WIDTH = 480
export const MAX_DOCKED_DETAILS_WIDTH = 600
export const MAX_DOCKED_SEQUENCER_HEIGHT = 600
